const EN = {
  administration: "administration",
  authentication: "authentication",
  confirmPassword: "confirm password",
  cancel: "cancel",
  createAccount: "create an account",
  code: "code",
  date: "date",
  delete: "delete",
  description: "description",
  dividerOr: "or",
  email: "e-mail",
  errorMessageAuthentication: "authentification error. This session has expired, please log back in",
  errorMessageLogin: "please enter your pseudo and password",
  errorMessageLogin2: "incorrect email or password",
  errorRegister: "error while creating your account. The pseudo has already been used by another user.",
  errorOccurredMessage: "an error occurred while performing this operation. Please retry later.",
  firstname: "firstname",
  image: "image",
  invalidForm: "some fields are not valid",
  language: "language",
  lastname: "lastname",
  login: "pseudo",
  modify: "modify",
  numero: "number",
  password: "password",
  register: "register",
  save: "save",
  signIn1: "sign in",
  signIn2: "sign into your account",
  signOut: "sign out",
  settings: "settings",
  statistics: "statistics",
  successRegister: "welcome. Your account creation has been successfully completed. You can access your account using the pseudo and password created",
  time: "time",
  validate: "validate",
  venue: "venue",

  dashboard: "dashboard",
  titleSurveyStart: "let's start creating your first survey !",
  createSurvey: "create a survey",
  createNewSurvey: "create a new survey",
};
  
  export { EN };