const FR = {
  administration: "administration",
  authentication: "authentification",
  confirmPassword: "confirmation mot de passe",
  cancel: "annuler",
  createAccount: "créer un compte",
  code: "code",
  date: "date",
  delete: "supprimer",
  description: "description",
  dividerOr: "ou",
  email: "e-mail",
  errorMessageAuthentication: "erreur d'authentification. Cette session a expiré, veuillez vous reconnecter encore une fois.",
  errorMessageLogin: "renseignez le pseudo et le mot de passe",
  errorMessageLogin2: "émail ou mot de passe incorrect",
  errorRegister: "erreur lors de la création de votre compte. Le pseudo a déjà été utilisé par un autre utilisateur.",
  errorOccurredMessage: "une erreur est survenue lors de l'exécution de cette opération. Veuillez rééssayer ultérieurement.",
  firstname: "prénom",
  image: "image",
  invalidForm: "certains champs ne sont pas valides",
  language: "langue",
  lastname: "nom",
  login: "pseudo",
  modify: "modifier",
  numero: "numéro",
  password: "mot de passe",
  register: "Inscription",
  save: "enregister",
  signIn1: "connexion",
  signIn2: "connectez-vous à votre compte",
  signOut: "déconnexion",
  resultats: "résultats",
  statistics: "statistiques",
  successRegister: "bienvenue. La création de votre compte a été effectuée avec succès et vous pouvez y accéder en utilisant l'dentifiant et le mot de passe créés.",
  time: "heure",
  validate: "valider",
  venue: "adresse",

  dashboard: "tableau de bord",
  titleSurveyStart: "commençons à créer votre premier sondage !",
  createSurvey: "créer un sondage",
  createNewSurvey: "créer un nouveau sondage",
};

export { FR };